# Note! Run the react client app (and not the surrounding dotnet framework)
# docker-compose up -d --build
# or only
# docker-compose up -d
version: '3.7'

services:
  niftymint:
    container_name: niftymint
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    expose:
      - '3030'
    ports:
      - '3030:3000'

# Remember to start the network before running this file:
# $ docker network create mydockernet
#
# Then you can start each of the docker-compose.yml files like this:
# $ docker-compose -f project_one/docker-compose.yml up -d
# $ docker-compose -f project_two/docker-compose.yml up -d
networks:
  default:
    external:
      name: mydockernet
